"""empty message

Revision ID: 7c92db350cd4
Revises: 97428d7bdca7
Create Date: 2019-05-17 09:54:03.350372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c92db350cd4'
down_revision = '97428d7bdca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lat', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('lon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lon')
    op.drop_column('user', 'lat')
    # ### end Alembic commands ###
